### ISSUE TITLE
Unique validator?

### ISSUE THREAD

**Issue by luisjuniorj** [holidayextras/jsonapi-server#104]
Hi, just getting started with this incredible lib, Is there an unique validator?

**Comment by theninj4** [comment]
Hi @luisjuniorj - I'm not sure I understand the question - can you elaborate on "unique validator"? If you're referring to Joi validation rules their API reference docs are here: https://github.com/hapijs/joi/blob/v8.0.5/API.md

**Comment by theninj4** [comment]
The heading you're looking for is titled "any.allow(value)"
