### ISSUE TITLE
Setting relationship while creating resource?

### ISSUE THREAD

**Issue by mmiller42** [holidayextras/jsonapi-server#105]
Say I'm creating a blog app and I need to create a new post while setting `author` to be the current user's object.

Is this possible? It's possible that this issue could actually relate to either the jsonapi-relationaldb-store or the jsonapi-client projects, but in any case, this example from the JSONAPI.org spec:

```
POST /photos HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```

seems to yield "photographer" as a null relationship in the result back, and a separate PATCH request must be issued to establish the photographer.

**Comment by theninj4** [comment]
It should be possible and should work how you've described. I'll give it a whirl over the bank holiday weekend and report back.

**Comment by theninj4** [comment]
Ok - the jsonapi-client module won't allow us to create a resource and set a relationship on it without first `.sync()`ing it. The reason being, without having a response from the server it's impossible to know if:
1. Does named relationship exist in the remote api?
2. Is the relationship a primary or foreign relation?
3. Is the relationship a hasOne or a hasMany?

Basically, validation is impossible without a response from the sever. 

There's also a related issue around creating two resources relating one to the other, without first sync'ing both resources to the remote API. Sync'ing a resource allows the remote API to assign it a uuid, allowing the relationship to exist.

It's certainly possible to tweak jsonapi-client to allow us to blindly create and assign to relationships, although there's a lot of error handling to think about.

**Comment by theninj4** [comment]
This is fixed now :+1: Thanks for brining it to my attention.
