### ISSUE TITLE
Example App Startup

### ISSUE THREAD

**Issue by mattklinker** [holidayextras/jsonapi-server#107]
Thanks for the great project, it looks nice and I'm looking forward to putting all the work to use.  I'm having trouble understanding something in your example though, note - I'm rather new to this environment so it could be simple misunderstanding on my part.

In all of the examples resource and handler files, you require jsonApi as require("../../.") and in server.js there is a server var exported whereas in the readme tldr it does a require("jsonapi-server") and there is no server var defined/exported.

Could you explain the difference, or perhaps point me to a resource that would explain how these 2 work? I've been able to get your example app up and running without issue, but when I try to simply import the package and setup my own project I don't get any of my example data returned and it feels to me that I'm doing this setup potentially incorrectly.  Is there a sample showing usage while referenced as package rather than included as project source?

Thanks again, project looks great besides my own troubles getting started!

**Comment by theninj4** [comment]
In the example server we do a `require("../../.")`, which resolves to the root of the project. If you attempt to require a folder path, node will look for a `package.json` file within in, and attempt to load the folder as though it were a real module located within a `node_modules` folder. 

This should get you up and running:
1. Create a new folder somewhere
2. `cd` into it
3. `npm install jsonapi-server`
4. Create a file called `server.js`
5. Drop the code in the `tl;dr` block into `server.js` and save it
6. `node server.js`
...and you should be away :+1: 

Your folder structure should look like this:
```
.
├── node_modules
│   └── jsonapi-server
└── server.js
```

**Comment by theninj4** [comment]
I'm going to close this issue, you're welcome to re-open it if you still have difficulties :+1:

**Comment by mattklinker** [comment]
Sorry for the slow response, but I really appreciate your help in understanding this.
