### ISSUE TITLE
Lets make supporting of unique fields 

### ISSUE THREAD

**Issue by slonofanya** [holidayextras/jsonapi-server#115]
Example:
```javascript
jsonApi.define({
  resource: "example",
  handlers: new jsonApi.MemoryHandler(),
  attributes: {
    title: jsonApi.Joi.string(),
    name: jsonApi.Joi.string().unique(), // When we create or update this field - check for unique and show warnings
  }
});
```

**Comment by slonofanya** [comment]
@theninj4, @pmcnr-hx, what do you think?

**Comment by theninj4** [comment]
There are two perspectives to consider here:

1. **When using a stock resourceHandler** (eg, the Mongo handler or the RelationalDB handler) - For these situations the best place to enforce uniqueness will be directly on the data store, be adding some kind of unique index on the necessary properties.

2. **When using a custom resourceHandler** (eg, consuming another API or internal system) - For these situations the best place to enforce uniqueness will be within the custom resource handler, where the author will be best placed to know how to efficiently decide if a given value is acceptable. 

Adding something to the Joi schema may add value in terms of autogenerating documentation, but I think it'll lead to a less-than-ideal implementation if we were to try and use it to magically change the behaviour of a handler.
