### ISSUE TITLE
Included relationships fail when host and protocol are unspecified.

### ISSUE THREAD

**Issue by dlras2** [holidayextras/jsonapi-server#119]
To reproduce:

1. Run the example server
2. Query `http://localhost:16006/articles?include=author`
3. Observe the `included` people are included
4. Remove `protocol` and `hostname` from `setConfig` in `index.js`
5. Rerun the above query
6. Observe the `included` people are now missing

While including the protocol and hostname fixes the inclusions, it also prepends it to all the links. This is fine as long as the outgoing links match the consuming service, but doing any sort of port mapping, load balancing, hostname redirects, etc, means that the exposed links do not include the expected hostnames. Leaving the links host-less allows this, and is allowed by the spec ([e.g.](http://jsonapi.org/format/#fetching-relationships))

**Comment by nsantorello** [comment]
@dlras2 I ran into this issue today as well.  It looks like the `include` functionality works by making a separate web request(s) to the `related` URL(s) for you.  That web request fails if the URL is not absolute (and uses the `setConfig` params to construct that URL).

I fixed this in a fork (haven't written tests and not yet ready for a PR) and you can see the changes are quite simple: https://github.com/SeedDev/jsonapi-server/commit/296b59ebc24203e463c80511b162f2aa737c1604

**Comment by theninj4** [comment]
I've thrown together something I've been meaning to do for a while. It solves many issues, one of which being what you guys are experiencing. I've tried to reproduce this with my changes, and it looks fixed. It'd be great if one of you could independently verify it for me?

**Comment by nsantorello** [comment]
@theninj4 I can confirm that latest in your branch `rerouter` fixes this issue.

**Comment by theninj4** [comment]
Awesome, thanks @nsantorello - really appreciate you taking the time to help :+1: I'll get my team to review the PR tomorrow (they need to be aware of the change) and hopefully we'll get a new version out sometime Tuesday.
