### ISSUE TITLE
providing links on the root endpoint

### ISSUE THREAD

**Issue by jcteague** [holidayextras/jsonapi-server#121]
I was reviewing the example and the code and I was expecting the different endpoints to be available on the api root as links.  When using hypermedia apis, I expose all available endpoints in the links collection of the root endpoint.  That way clients only know one url to access the api, all others are provided.

If I wanted to add a resource that would be exposed on the api root, how would I do that?  And how would I set what links or embed resources on the root?

Thanks

**Comment by theninj4** [comment]
Hi @jcteague - The JSON:API specification doesn't currently cover a response for the root endpoint of the API (http://api.example.com/ or whatever for anyone else reading this). If you're looking for a way of enabling API discovery, you should check out the automatic swagger documentation (https://github.com/holidayextras/jsonapi-server/blob/master/documentation/swagger.md).

Until the JSON:API specification includes a section covering the root endpoint, I'm not going to go off-spec by putting something there. If you want to do so in your own fork, I'd suggest you take this file https://github.com/holidayextras/jsonapi-server/blob/master/lib/routes/_swagger.js copy + paste it into the same folder, then tweak its behaviour as desired.

**Comment by jcteague** [comment]
@theninj4 Thanks for the response.  It's your project so I complete respect your choice, however this is covered by the  [jsonapi documentation ](http://jsonapi.org/format/#document-top-level) in the Top Level section.

the Top Level section **MUST** provide a valid response and **MAY** contain a jsonapi response object.

Swagger is not what I mean, as that is for human consumption.  Providing a top level response is an important part of an Hypermedia API, as it provides decoupling from the client and server by not needing to know any urls except the root / top level url.

**Comment by theninj4** [comment]
@jcteague I interpreted that specification slightly differently to you. I read that section as a general definition of all JSON:API payloads, as in, the root document that applies to every request. I don't think it's referring to the root endpoint of the API.

Right now, the only place in the spec that doesn't prohibit us adding extra bits and pieces is the `meta` block. I guess we could argue the spec would allow the following payload, but only because it doesn't strictly prohibit it:

```
{
  jsonapi: {
    version: "1.0"
  },
  meta: {
    description: "This block shows up in the root node of every payload",
    resources: {
      "articles": "http://localhost:16006/rest/articles",
      "comments": "http://localhost:16006/rest/comments",
      "people": "http://localhost:16006/rest/people",
      "photos": "http://localhost:16006/rest/photos",
      "tags": "http://localhost:16006/rest/tags"
    }
  },
  links: {
    self: "http://localhost:16006/rest/"
  }
}
```

The spec says:
```
A document MAY contain any of these top-level members:

* jsonapi: an object describing the server’s implementation
* links: a links object related to the primary data.
* included: an array of resource objects that are related to the primary data and/or each other (“included resources”).
```
The `data` property must be a "primary data" block, which should only appear in "/:resourceType/" URLs. The `links` property must relate to the primary data block, so we can't put custom data in there.

**Comment by jcteague** [comment]
Fair enough.  If you look at the (Endpoint Example)[https://github.com/endpoints/endpoints-example] their root object looks like this:

```json
{
  "authors": "/v1/authors?include={books,books.chapters,photos}&filter[{id,name,alive,dead,date_of_birth,date_of_death,born_before,born_after}]",
  "books": "/v1/books?include={chapters,firstChapter,series,author,stores,photos}&filter[{author_id,series_id,date_published,published_before,published_after,title}]",
  "chapters": "/v1/chapters?include={book}&filter[{book_id,title,ordering}]",
  "photos": "/v1/photos?include={imageable}",
  "series": "/v1/series?include={books,photos}&filter[{title}]",
  "stores": "/v1/stores?include={books,books.author}"
}
```
Is what I'm describing.

Thanks,
John

**Comment by theninj4** [comment]
Sadly it looks like that project is only loosely compliant with the JSON:API specification. After browsing their example it looks like they've ticked most of the "MUST" boxes, but overall it's not a shining example of what a good JSON:API compliant API looks like.

From your own link, the second paragraph, states the root object you've quoted is not compliant:
```
A document MUST contain at least one of the following top-level members:

* data: the document’s “primary data”
* errors: an array of error objects
* meta: a meta object that contains non-standard meta-information.
```

If it bothers you enough, you should to head over to https://github.com/json-api/json-api/issues and suggest an extension to the spec to include resource discovery. If they explicitly allow it, I'll happily add it in :+1:

**Comment by jcteague** [comment]
Yes. That's why I quickly discarded it as a viable option.  Yours is
definitely the most compliant nodejs server option.

**Comment by challarao** [comment]
@jcteague
Hi John,

Were you able to solve this problem?

Thank you

**Comment by paparomeo** [comment]
Is this something now covered by the spec @challarao?

**Comment by challarao** [comment]
Hi @paparomeo

I don't think so. Also, there is something misunderstood about JSON API. 

JSON API is intended standardize JSON usage across apis. But I thought it has something to do particularly with pure REST/HATEOS REST. It doesn't seem to be its goal.

Also, there is no mention of REST at all in jsonapi.org. Hence the problem is solved :)

Thank you
