### ISSUE TITLE
urlencoded query parameters broken

### ISSUE THREAD

**Issue by pmcnr-hx** [holidayextras/jsonapi-server#122]
As reported by @jbockerstette [here](https://github.com/holidayextras/jsonapi-store-mongodb/issues/28), urlencoded query parameters (as those generated by swagger.io) are not being handled correctly:

> Pedro,
> 
> Here is the real problem.
> 
> If you paste this into the browser it works as expected.
> http://107.170.10.170:16006/1/articles?fields[articles]=title
> 
> However, if you use swagger.io UI, swagger turns the above statement to
> this:
> http://107.170.10.170:16006/1/articles?fields=%5Barticles%5D%3Dtitle
> 
> swagger encodes the brackets and equals into %5B, %5D and %3D.  It appears
> that this encoding is breaking it. Maybe all you need to do is decode it
> before processing.
> 
> I apologize for poor problem definition previously.
> 
> Jim

**Comment by theninj4** [comment]
This one does actually function correctly. The second link is wrong, there is a rogue `=` in the wrong place - it should look like this:
http://localhost:16006/rest/articles?fields%5Barticles%5D%3D=title

Notice the difference:
fields=%5Barticles%5D%3Dtitle
vs:
fields%5Barticles%5D%3D=title

If the URL on the issue came directly from Swagger, there's probably an issue in their repo around sending nested GET params. It's out of our control :(

**Comment by jbockerstette** [comment]
Oliver,
Thanks for looking into this. You are correct. However, I still think there
is a problem with urlencoding.

*This works as expected. No encoding.*
http://107.170.10.170:16006/1/articles?fields[articles]=title

*Returns:*

{"jsonapi":{"version":"1.0"},"meta":{"description":"This block shows
up in the root node of every
payload","page":{"offset":0,"limit":50,"total":4}},"links":{"self":"http://localhost:16006/1/articles?fields[articles]=title"},"data":[{"type":"articles","id":"de305d54-75b4-431b-adb2-eb6b9e546014","attributes":{"title":"NodeJS
Best Practices"},"links":{"self":"http://localhost:16006/1/articles/de305d54-75b4-431b-adb2-eb6b9e546014"},"relationships":{"author":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/de305d54-75b4-431b-adb2-eb6b9e546014/relationships/author","related":"http://localhost:16006/1/articles/de305d54-75b4-431b-adb2-eb6b9e546014/author"},"data":{"type":"people","id":"cc5cca2e-0dd8-4b95-8cfc-a11230e73116","meta":{"updated":"2010-11-06"}}},"tags":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/de305d54-75b4-431b-adb2-eb6b9e546014/relationships/tags","related":"http://localhost:16006/1/articles/de305d54-75b4-431b-adb2-eb6b9e546014/tags"},"data":[{"type":"tags","id":"7541a4de-4986-4597-81b9-cf31b6762486"}]},"photos":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/de305d54-75b4-431b-adb2-eb6b9e546014/relationships/photos","related":"http://localhost:16006/1/articles/de305d54-75b4-431b-adb2-eb6b9e546014/photos"},"data":[]},"comments":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/de305d54-75b4-431b-adb2-eb6b9e546014/relationships/comments","related":"http://localhost:16006/1/articles/de305d54-75b4-431b-adb2-eb6b9e546014/comments"},"data":[{"type":"comments","id":"3f1a89c2-eb85-4799-a048-6735db24b7eb"}]}},"meta":{"updated":"2011-05-10"}},{"type":"articles","id":"1be0913c-3c25-4261-98f1-e41174025ed5","attributes":{"title":"Linux
Rocks"},"links":{"self":"http://localhost:16006/1/articles/1be0913c-3c25-4261-98f1-e41174025ed5"},"relationships":{"author":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/1be0913c-3c25-4261-98f1-e41174025ed5/relationships/author","related":"http://localhost:16006/1/articles/1be0913c-3c25-4261-98f1-e41174025ed5/author"},"data":{"type":"people","id":"d850ea75-4427-4f81-8595-039990aeede5"}},"tags":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/1be0913c-3c25-4261-98f1-e41174025ed5/relationships/tags","related":"http://localhost:16006/1/articles/1be0913c-3c25-4261-98f1-e41174025ed5/tags"},"data":[{"type":"tags","id":"2a3bdea4-a889-480d-b886-104498c86f69"}]},"photos":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/1be0913c-3c25-4261-98f1-e41174025ed5/relationships/photos","related":"http://localhost:16006/1/articles/1be0913c-3c25-4261-98f1-e41174025ed5/photos"},"data":[{"type":"photos","id":"aab14844-97e7-401c-98c8-0bd5ec922d93"},{"type":"photos","id":"72695cbd-e9ef-44f6-85e0-0dbc06a269e8"}]},"comments":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/1be0913c-3c25-4261-98f1-e41174025ed5/relationships/comments","related":"http://localhost:16006/1/articles/1be0913c-3c25-4261-98f1-e41174025ed5/comments"},"data":[]}}},{"type":"articles","id":"d850ea75-4427-4f81-8595-039990aeede5","attributes":{"title":"How
to AWS"},"links":{"self":"http://localhost:16006/1/articles/d850ea75-4427-4f81-8595-039990aeede5"},"relationships":{"author":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/d850ea75-4427-4f81-8595-039990aeede5/relationships/author","related":"http://localhost:16006/1/articles/d850ea75-4427-4f81-8595-039990aeede5/author"},"data":{"type":"people","id":"32fb0105-acaa-4adb-9ec4-8b49633695e1"}},"tags":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/d850ea75-4427-4f81-8595-039990aeede5/relationships/tags","related":"http://localhost:16006/1/articles/d850ea75-4427-4f81-8595-039990aeede5/tags"},"data":[{"type":"tags","id":"8d196606-134c-4504-a93a-0d372f78d6c5"}]},"photos":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/d850ea75-4427-4f81-8595-039990aeede5/relationships/photos","related":"http://localhost:16006/1/articles/d850ea75-4427-4f81-8595-039990aeede5/photos"},"data":[{"type":"photos","id":"aab14844-97e7-401c-98c8-0bd5ec922d93"}]},"comments":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/d850ea75-4427-4f81-8595-039990aeede5/relationships/comments","related":"http://localhost:16006/1/articles/d850ea75-4427-4f81-8595-039990aeede5/comments"},"data":[]}}},{"type":"articles","id":"fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5","attributes":{"title":"Tea
for Beginners"},"links":{"self":"http://localhost:16006/1/articles/fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5"},"relationships":{"author":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5/relationships/author","related":"http://localhost:16006/1/articles/fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5/author"},"data":{"type":"people","id":"ad3aa89e-9c5b-4ac9-a652-6670f9f27587"}},"tags":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5/relationships/tags","related":"http://localhost:16006/1/articles/fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5/tags"},"data":[{"type":"tags","id":"6ec62f6d-9f82-40c5-b4f4-279ed1765492"},{"type":"tags","id":"7541a4de-4986-4597-81b9-cf31b6762486"}]},"photos":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5/relationships/photos","related":"http://localhost:16006/1/articles/fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5/photos"},"data":[{"type":"photos","id":"4a8acd65-78bb-4020-b9eb-2d058a86a2a0"}]},"comments":{"meta":{"relation":"primary","readOnly":false},"links":{"self":"http://localhost:16006/1/articles/fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5/relationships/comments","related":"http://localhost:16006/1/articles/fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5/comments"},"data":[{"type":"comments","id":"6b017640-827c-4d50-8dcc-79d766abb408"}]}}}],"included":[]}


*This does not work: (The only difference is encoding)*
http://107.170.10.170:16006/1/articles?fields=%5Barticles%5D%3Dtitle

*Returns:*

{"jsonapi":{"version":"1.0"},"meta":{"description":"This block shows
up in the root node of every
payload"},"links":{"self":"http://localhost:16006/1/articles"},"errors":[{"status":"403","code":"EFORBIDDEN","title":"Invalid
field selection","detail":"articles do not have property "}]}


*This does not work:*
curl -X GET \
   -H "Content-Type: application/vnd.api+json" \
   -H 'Accept: application/vnd.api+json' \
   'http://107.170.10.170:16006/1/articles?fields%5Barticles%5D%3Dtitle'

*Returns:*

{"jsonapi":{"version":"1.0"},"meta":{"description":"This block shows
up in the root node of every
payload"},"links":{"self":"http://localhost:16006/1/articles"},"errors":[{"status":"403","code":"EFORBIDDEN","title":"Invalid
field selection","detail":"articles do not have property "}]}

**Comment by theninj4** [comment]
In your broken examples, the format of the query string is incorrect:

```
articles?fields=%5Barticles%5D%3Dtitle
```
which decodes to
```
articles?fields=[articles]=title
```
The `=` after `fields` is invalid, it shouldn't be there.

**Comment by jbockerstette** [comment]
Oliver,

I am very sorry about my mistake in putting that = in there. You are
correct about that.

However, it does not work if you take that out. In addition, my curl did
not have that extra = in it and it also fails.
Here is the corrected link which fails. As you can see, I removed the =.

This fails.
*This does not work: (The only difference is encoding)*
http://107.170.10.170:16006/1/articles?fields%5Barticles%5D%3Dtitle
<http://107.170.10.170:16006/1/articles?fields=%5Barticles%5D%3Dtitle>

{"jsonapi":{"version":"1.0"},"meta":{"description":"This block shows
up in the root node of every
payload"},"links":{"self":"http://localhost:16006/1/articles"},"errors":[{"status":"403","code":"EFORBIDDEN","title":"Invalid
field selection","detail":"articles do not have property "}]}

**Comment by theninj4** [comment]
Thanks for persevering, it's very interesting. You're right that this fails:
```
articles?fields%5Barticles%5D=title

**Comment by theninj4** [comment]
Thanks for persevering, it's very interesting. You're right that this fails:
```
articles?fields%5Barticles%5D%3Dtitle
```
and it's because its supposed to look like this:
```
articles?fields%5Barticles%5D=title
```

The equals characters aren't meant to be url encoded - encoding the equals characters implies they're meant to be interprete as being non-special. For example, if I wanted to send the string `1=1` as a query parameter named `equation`, I'd send it as `equation=1%3D1`. 

In your broken URL, `fields%5Barticles%5D%3Dtitle` is treated as the variable name, with no associated value, due to no `=` character.

I expect the default behaviour for Swagger is to take everything within the "value" field and URL encode it. That's converting your value  of `[articles]=title` into `%5Barticles%5D=title`, it's then glueing that value into the URL after the key of `fields=`, resulting in your original broken query string.

The behaviour here is correct. If you run the example server via `DEBUG=jsonApi:* npm start` and play around with the URL params, you'll see how the encoding effects the params. We're using the industry standard ExpressJS url parser and it's behaving exactly as I expect it to.

**Comment by jbockerstette** [comment]
Thanks. I will work with the swagger guys. Great job.
