### ISSUE TITLE
Row level access?

### ISSUE THREAD

**Issue by leondewey** [holidayextras/jsonapi-server#123]
How would you go about restricting row level access?

**Comment by pmcnr-hx** [comment]
Do you mean restrict access to resources based on some kind of authorisation mechanism, @leondewey?

**Comment by leondewey** [comment]
@pmcnr-hx Yes kind of, I can see how todo it on a resources level but what about if that resources was posts and you only want a user to be able to CRUD there own posts?

**Comment by theninj4** [comment]
Hi @leondewey - We combine the authentication hook with custom wrappers around the CRUD handlers. Our auth hooks look something like this:
```
jsonApi.authenticate(function(request, callback) {
  // validate headers / cookie / whatever, check user is logged in, etc.
  // ...If OK, then attach user data to request
  request._userData = { };
  return callback();
});
```

We then wrap the base database handlers with some logic that enforces filtering upon the database, by using `request._userData` to limit the scope of the query. You can find an example of that in the comments of the example here: https://github.com/holidayextras/jsonapi-server/blob/master/documentation/suggested-project-structure.md#example-handler (you'd add to `request.filter` on the example line that currently reads `tweak something?`).

**Comment by leondewey** [comment]
Thank you very much! That's really cool.
