### ISSUE TITLE
HTTP 403 returned as default error is not always appropriate

### ISSUE THREAD

**Issue by BryceCicada** [holidayextras/jsonapi-server#132]
Hi, 

I'm using jsonapi-server in my project.  However, I wonder if the use of status code HTTP 403 Forbidden is appropriate where it occurs.  In particular, my project has no permissions etc, so there is nothing that would forbid a user from working with resources.  If it did, I would expect my handlers to manage these permissions... not jsonapi-server itself.

Suggestions:

1. If I create a handler with no _create_ function, then I have not allowed creation of this resources and POSTing should return HTTP 405 Method Not Allowed.  Similarly for _update_ and _delete_ with HTTP PUT and DELETE.
2. If I POST without any data, then this is a bad request and POSTing should return HTTP 400 Bad Request
3. If I POST with data that does not match the schema, then this is a bad request and POSTing should return HTTP 400 Bad Request.

**Comment by BryceCicada** [comment]
Here's a suggested change https://github.com/holidayextras/jsonapi-server/pull/133

**Comment by theninj4** [comment]
The portion of the spec I was looking at when I first picked `403` was:
```
A server MUST return 403 Forbidden in response to an unsupported request to create a resource with a client-generated ID.
...
A server MUST return 403 Forbidden in response to an unsupported request to update a resource or relationship.
...
If the client makes a DELETE request to a URL from a relationship link the server MUST delete the specified members from the relationship or return a 403 Forbidden response.
...
A server MUST return 403 Forbidden in response to an unsupported request to update a relationship.
```

They do however state:
```
A server MAY respond with other HTTP status codes.
```

So I guess it is up for debate how to interpret `an unsupported request`. Right now both of the following are considered unsupported:

* Invalid request payloads.
* Requesting functionality that isn't supported by the resource handler.

Searching the spec for `405 ` doesn't match anything at all. Whilst I think a `405 Method Not Allowed` might read a bit better than a `403 Forbidden`, the spec never mentions 405 and it implies a 403 is the correct response code. I'm reluctant to change this unless the definition within the JSON:API spec changes.

Searching the spec for `400 ` does reveal this:
```
If a server encounters a query parameter that does not follow the naming conventions above, and the server does not know how to process it as a query parameter from this specification, it MUST return 400 Bad Request.
```
which makes me think that you're correct with points 2 and 3 :+1:

**Comment by BryceCicada** [comment]
I see.

I'm new to JSON:API, and I hadn't consulted the spec.  Rather, I was thinking about other RESTful APIs that I've used and the HTTP 1.1 spec.

I agree completely that jsonapi-server should adhere to JSON:API spec, and my point 1 should be discarded.

**Comment by BryceCicada** [comment]
Reading the JSON:API spec, I'm satisfied that jsonapi-server works well, :).  

Closing this issue.  Thanks for the clarification.
