### ISSUE TITLE
Allow resource namespaces in URL

### ISSUE THREAD

**Issue by BryceCicada** [holidayextras/jsonapi-server#136]
HI, 

Suppose my resources are logically grouped in some way.  Say, I have a groups of resources relating to travel and some other group of resources relating to finance.  Conceptually, this is like having different namespaces for resources.  Is it possible in jsonapi-server to have this logical structure of resources represented in the url? eg

- http://www.myserver.com/resources/travel/schedules
- http://www.myserver.com/resources/finance/expenses

I can only see how to configure a base url http://www.myserver.com/resources/ and then all resources are presumed to hang directly from that, like http://www.myserver.com/resources/schedules etc, rather than in some logical grouping of sub-urls including _travel_ and _finance_

Right now, the only way I can think of achieving this is to put a reverse proxy in front of (perhaps multiple) jsonapi-server instances.  The reverse proxy can then route the urls.  Seems a bit overkill.  Is there a better way?

Is it worth me investigating such a change to jsonapi-service and send a PR?

**Comment by pmcnr-hx** [comment]
Interesting question. I am not sure if the spec provides any guidance in this matter. You could name your resources `travel_schedules`, `finance_expenses` and have your reverse proxy rewrite `http://www.myserver.com/resources/travel/schedules` to `http://www.myserver.com/resources/travel_schedules`. That should be a fairly straightforward solution.

**Comment by theninj4** [comment]
This has come up within the JSON:API spec:
https://github.com/json-api/json-api/issues/850

The long and short of it is that the urls shouldn't be changed to accommodate namespaces, and you should hyphenate your resource names if you need to add namespaces. The spec may well change (or be added to) in the future.

**Comment by BryceCicada** [comment]
I'm learning the following:

- JSON:API resources have a type
- JSON:API doesn't care where resources are located.  
- jsonapi-server implementation hangs all resources off a root url.
- some other implementation could hang each resource off arbitrary urls.

Is that so?

If I understand, json-api/json-api#850 is discussing how namespaces can be added to types.  However, I'm content with flat types.  I'm wondering if resources can be accessed with urls that reflect some other structure, not just the flat type structure.

I stress that this is a very minor issue.  jsonapi-server is extremely useful as it is.

**Comment by BryceCicada** [comment]
Reading the JSON:API recommendations at http://jsonapi.org/recommendations/

> When determining an API’s URL structure, it is helpful to consider that all of its resources exist in a single “reference document” in which each resource is addressable at a unique path. Resources are grouped by type at the top level of this document.

I suppose jsonapi-server should remain in accordance with this recomendation.  Closing this.

**Comment by ephrin** [comment]
@pmcnr-hx JFYI `-` is not valid character on resources.
@BryceCicada you can try to add static resources with relations to other resources that will be disposed as static identifiers in the system. But, still, a lack in naming of types (type vs path) will cause a mess with definitions.
