### ISSUE TITLE
Using with mongoose

### ISSUE THREAD

**Issue by seawatts** [holidayextras/jsonapi-server#139]
Is the assumption here that if I am using mongoose and using https://github.com/holidayextras/jsonapi-store-mongodb that you define your models twice? Once as a mongoose schema and once in the jsonapi-server resource format?

**Comment by pmcnr-hx** [comment]
Hi @seawatts. The idea behind the `jsonapi-store-mongodb`, is that it handles persistence of your resources automatically and transparently for you, based on the Joi schema of the resource. If you have a compelling case for managing persistence yourself with Mongoose, you'll need to create a [custom handler](https://github.com/holidayextras/jsonapi-server/blob/master/documentation/handlers.md) for your resources.

**Comment by seawatts** [comment]
I guess I should have given you my use case. 
When performing an algorithm on the server I need to go out to mongo to get all my user model. I then need to create a new group model after that. So my question is what is a good pattern for performing those actions

**Comment by pmcnr-hx** [comment]
Are these Mongo collections just meant to be accessed through `jsonapi-server` or are they accessed directly elsewhere? These are architectural decisions which really depend on a number of factors.

**Comment by seawatts** [comment]
Outside the API

**Comment by pmcnr-hx** [comment]
From what I can understand of your problem I think, as I recommended initially, that you'll be better off ignoring `jsonapi-store-mongodb` and creating  [custom handlers](https://github.com/holidayextras/jsonapi-server/blob/master/documentation/handlers.md) for your resources based on your Mongoose models.

**Comment by seawatts** [comment]
Interesting. I might try that. 

Here is an example of my use case. It should be pretty basic.
https://gist.github.com/seawatts/ccae398b51aeb7bc5a60c2627bc85b4e

**Comment by pmcnr-hx** [comment]
You shouldn't mix `mongoose` and `jsonapi-store-mongodb` (you can of course, but I wouldn't recommend it). You should go with either `jsonapi-store-mongodb` **or** `mongoose` + custom handler. Given the clarification in your gist, there is another option which is to just use `jsonapi-store-mongodb` (no `mongoose`) and use [`jsonapi-client`](https://github.com/holidayextras/jsonapi-client) in the same process to connect back to the server and create the resources. Hope that clarifies it.
