### ISSUE TITLE
Example POST new comment fails with 403 if you specify the article relationship

### ISSUE THREAD

**Issue by jbockerstette** [holidayextras/jsonapi-server#149]
If I try to POST a new comment with the article relationship specified, it fails with a 403.

I believe the problem is in create.js lines 36-44. Also of note is that in comments.js, article is specified as Joi.belongsToOne. It appears that a POST will fail on any resource if you try to specify the relationship for the Joi.belongsToOne attribute.

```
curl -X POST --header 'Content-Type: application/vnd.api+json' --header 'Accept: application/vnd.api+json' -d '{
  "data": {
    "attributes": {
      "body": "string"
      
    },
    "relationships": {
      "article": {
        "data": {
          "type": "articles",
          "id": "de305d54-75b4-431b-adb2-eb6b9e546014",
          "meta": {}
        }
      }
    }
  }
}' 'http://107.170.10.170:16006/rest/comments'
```

Response body:

```
{
  "jsonapi": {
    "version": "1.0"
  },
  "meta": {
    "description": "This block shows up in the root node of every payload"
  },
  "links": {
    "self": "http://localhost:16006/rest/comments"
  },
  "errors": [
    {
      "status": "403",
      "code": "EFORBIDDEN",
      "title": "Param validation failed",
      "detail": [
        {
          "message": "\"article\" is not allowed",
          "path": "article",
          "type": "object.allowUnknown",
          "context": {
            "key": "article"
          }
        }
      ]
    }
  ]
}

```

**Comment by theninj4** [comment]
In this example, the definition of comments lists `article` as being a foreign relationship:
``
    article: jsonApi.Joi.belongsToOne({
      resource: "articles",
      as: "comments"
    })
```
This means no `comments` resources should ever contain data about their article - the relevant documentation for what's going on can be found here: https://github.com/holidayextras/jsonapi-server/blob/master/documentation/foreign-relations.md

**Comment by jbockerstette** [comment]
That makes sense. The only reason I tried to do this was that the resulting
swagger implies that this can be done. It might be nice to generate swagger
that does not show this as an option in the POST. Just a thought. It is not
critical for me.

Thanks.

**Comment by theninj4** [comment]
Hi @jbockerstette - You've got a good point about the misleading docs, I'll convert this to an `enhancement` to try and find a resolutionn :+1:
