### ISSUE TITLE
Is there a way to add meta information to a Resource Object or an Identifier?

### ISSUE THREAD

**Issue by Artanis** [holidayextras/jsonapi-server#15]
I need to qualify a relationship with some data, which can be [accomplished with the `meta` object](http://discuss.jsonapi.org/t/metadata-about-relationships/86/2).

However, adding a meta object to an Resource Object Identifier (using the `mockHandlers`'s `examples` option) results in a `ValidationError: "meta" is not allowed`, and the server omits the offending Resource Object. The same error is received when attempting to create a Resource Object with meta information.

    jsonApi.define({
      resource: "example",
      attributes: {
        qualified_relationship: jsonApi.joi.many("other"),
      },
      examples: [
        {
          type: "example",
          qualified_relationship: [
            {type: "other", id: "1", meta: {quantity: "2"}}
          ],
          meta: {
            description: "It should also be possible to add a `meta` object to a document."
          }
        }
      ]
    })

    jsonApi.define({
      resource: "other"
      examples: [
        {type: "other", id: "1"}
      ]
    });

**Comment by hxoliverrumbelow** [comment]
Absolutely, its a straight forward addition. I'll see what I can do this weekend :+1:

**Comment by hxoliverrumbelow** [comment]
@Artanis does this behave as you'd expect?

**Comment by Artanis** [comment]
It does.

The only concern I have is that the meta member should be an object, and the pull types it as `Any`.

**Comment by hxoliverrumbelow** [comment]
Good call. I've also added some changes and test cases for creating and updating both resources and relationships metadata to prove it flows down to the handlers. This allows implementations to either accept changes to metadata, silently ignore invalid properties or respond with errors.
