### ISSUE TITLE
Swagger UI is generating curls that are not understood by jsonapi-server

### ISSUE THREAD

**Issue by jbockerstette** [holidayextras/jsonapi-server#152]
I have reported this bug to both projects (jsonapi-server) and swagger-ui project. Each project has responded that it is not a bug in their software. I am not an expert in this subject. All I know is that swagger does not work correctly with jsonapi-server when trying to pass params from the swagger ui to jsonapi-server. Please take a look at this issue and let me know what I should do. Thanks.
https://github.com/swagger-api/swagger-ui/issues/2159

**Comment by theninj4** [comment]
I honestly can't see this one being fixed - both projects are behaving as expected, the core issue is that it's very difficult to completely describe a JSON:API service (or any other hypermedia API) using Swagger.

From Swagger's perspective, any text an end user types into the "value" input fields within Swagger needs to be escaped. They are correct, they should indeed escape this data.

From JSON:API's perspective, we allow API consumers to use the `foo[bar]` URL query syntax to achieve complex queries. We can't (and shouldn't) document every possible set of options for all filter/include/sort/fields params.

The two ideas simply don't align.

I've taken the jsonapi-server automatic Swagger documentation as far as I felt worthwhile before the two ideas started to collide with one another. Ultimately JSON:API only supports 11 routes, those routes behave exactly the same regardless of what resources or relationships they involve. Theoretically we should only need to document those core 11 routes, and what each resource looks like. I've got a project going on the side to provide a better documentation interface for JSON:API, but it's on the backburner at the moment.

Swagger requires us to be very specific about what elements appear where, and it makes it nearly impossible to fully document a hypermedia API. For example - how can we document exactly what comes back in a request with an inclusion? It depends on the query parameters. Likewise, any field parameters break the Swagger docs.

Ultimately: Swagger doesn't play nicely with hypermedia API's.
