### ISSUE TITLE
jsonapi-server works incorrectly with prefix and existing express server

### ISSUE THREAD

**Issue by EJIqpEP** [holidayextras/jsonapi-server#160]
Hello. I have express server which renders react on any page except api pages. 
What I want to achive: jsonapi-server controls /api/* routes and my app.get controls all other urls.
Now when I go to any url with async data fetching, jsonapi-server renders page with empty object faster then my code. I thought base in config should solve this issue.
```javascript
app.get(/^\/(?!api).*/, ()=> {
// render react here
});
```
After this lines I put jsonApi initializing
```javascript
  const express = Object.keys(require.cache)
    .filter(i => i.match('/node_modules/express/index.js')).pop();

  require.cache[express].exports = function () {
    return app;
  };
  const jsonApi = require('jsonapi-server');
  jsonApi.setConfig({
    base: 'api'
  });

  fs.readdirSync(path.join(__dirname, '..', '/db/resources'))
    .filter(filename => /^[a-z].*\.js$/.test(filename))
    .map(filename => path.join(__dirname, '..', '/db/resources/', filename))
    .forEach(require);

  require('jsonapi-server/lib/routes/index.js').register();
```

And at the and I add listener on port

```javascript
app.listen(app.get('port'));
```

Upd: The message when I deploy to server is different
```javascript
{
name: "r",
message: "request to http://example.com/api/lessons failed, reason: getaddrinfo ENOTFOUND example.com example.com:80",
type: "system",
errno: "ENOTFOUND",
code: "ENOTFOUND",
endpoint: "lessons"
}
```

**Comment by EJIqpEP** [comment]
The easiest way to fix this is just separate api in other project and just proxy requests to jsonapi-server. It's much easier than to try to make them working together.

**Comment by theninj4** [comment]
Using separate projects is a good solution. If anyone is desperate to make it all work together as a whole, jsonapi-server exposes it's express instance like this:

https://github.com/holidayextras/jsonapi-server/blob/master/documentation/configuring.md#gaining-access-to-the-express-server

Slightly more documentation on the PR:
https://github.com/holidayextras/jsonapi-server/pull/153
