### ISSUE TITLE
Optional bypassing of post-processing filtering

### ISSUE THREAD

**Issue by pmcnr-hx** [holidayextras/jsonapi-server#161]
Look into allowing post-processing filtering to be optionally bypassed so data store side filtering is properly exercised by the relevant tests.

**Comment by theninj4** [comment]
We should be able to validate this by comparing the pagination block with the number of resulting resources. The post processing filter will remove resources but it will NOT twiddle the pagination counters (one of them is the claimed number of returned resources). If the two sources don't line up, the data store isn't filtering correctly.

**Comment by pmcnr-hx** [comment]
Sounds like a plan. I'll see about adding a test for this to avoid future regressions.
