### ISSUE TITLE
Is it possible to avoid overriding of handlers method?

### ISSUE THREAD

**Issue by EJIqpEP** [holidayextras/jsonapi-server#162]
Hi. I'm trying to implement adding slug automatically on create. In custom handler I can see that we can only fully override create method. There is no middleware to put beforeCreate.
My code is looking a bit ugly
```javascript
const handler = new MongoStore({
  url: mongoUrl
});

const oldCreate = handler.create.bind(handler);

handler.create = function (request, newResource, callback) {
  newResource.slug = 'testSlug';
  oldCreate(request, newResource, callback);
};
```
Is there a way to write code better?

**Comment by theninj4** [comment]
Not at this time, sorry. Some kind of middleware interface on the handler functions is an interesting idea, I'll keep it in mind :+1:
