### ISSUE TITLE
Filter in relationships doesn't filter correctly.

### ISSUE THREAD

**Issue by EJIqpEP** [holidayextras/jsonapi-server#174]
Hi. I'm doing data filtering according the examples in tests. 
```
/lessons?include=category&filter[category][name]=aa
```
So here I want to get all lessons what belongs to category with name aa.
In response it returns all lessons that I have. 

For comparison such filtering works correctly
```
/lessons?include=category&filter[category]=111
```

As a store I'm using jsonapi-store-mongodb.
My resource are:
```
jsonApi.define({
  namespace: 'json:api',
  resource: 'categories',
  handlers: categoryHandler,
  attributes: {
    name: jsonApi.Joi.string().required()
      .description('The name of category')
  }
});

jsonApi.define({
  namespace: 'json:api',
  resource: 'lessons',
  handlers: lessonHandler,
  attributes: {
    title: jsonApi.Joi.string().required()
      .description('The title of lesson'),
    category: jsonApi.Joi.one('categories')
  }
});
```

**Comment by theninj4** [comment]
Yes, this behaviour is correct.

The first query `/lessons?include=category&filter[category][name]=aa` is saying "Find me all lessons, then include all categories with a name of aa".

The second query `/lessons?include=category&filter[category]=111` is saying "Find me all lessons where the lesson category is 111".

The specification doesn't mention anything about a JSON:API compliant service needing to implement smart filtering based on combinations of nested inclusions and filters. It IS however something that may be nice to have at some point in the future...

**Comment by EJIqpEP** [comment]
Thanks a lot. Now I understand it. Because while viewing tests I didn't understand it correctly.
