### ISSUE TITLE
Event listeners / pre or post processing for resources.

### ISSUE THREAD

**Issue by adamlc** [holidayextras/jsonapi-server#176]
We're just starting to build a new API around jsonapi-server and loving it so far! 

I just had a query / suggestion. We have a requirement where we need to do various things either before or after a resource is created. The main requirement is we need to quota certain resources so we'd need to hook in before records are created and after they're created. Returning an error if their quota is full or adding to their quota once a record is inserted.

At the moment the only way of doing this from what I can see if using a Custom Handler. Whilst this would work it would mean creating a Custom Handler for each resource that needs a hook with only subtle differences.

What are people's thoughts on having a common way to hook into these events? It would be great if this was built into the core so each handler didn't need to be rebuilt. Sorry for the waffle, I hope it makes sense!

**Comment by theninj4** [comment]
This has come up before in #162, and we ran in to a challenge in production a few months back whereby we wanted to add some custom authentication to a bunch of resources backed by the relational data store, we solved it by creating a custom handler that accepts another handler and allows us to inject custom functionality around each handler action.

I'll look in to this issue today and see if I can find a syntactically pleasant solution that can be open sourced.

**Comment by theninj4** [comment]
@adamlc does the above PR help overcome some of your challenges?

**Comment by adamlc** [comment]
@theninj4 that looks like it should do the trick! I'll have a play later and let you know how it goes :)

**Comment by adamlc** [comment]
@theninj4 Just to let you know that worked perfectly for our use case, can't thank you enough!
