### ISSUE TITLE
Allow dynamic metadata

### ISSUE THREAD

**Issue by gauthierm** [holidayextras/jsonapi-server#177]
In the server config you can currently specify static metadata. This data is fixed after the server starts. I would like to include a response timestamp in the metadata for synchronization between client and server but there is no obvious way to do it.

I'd like to be able to specify a function or a special kind of handler object for the request metadata.

**Comment by adamlc** [comment]
This would also be useful for me too :)

**Comment by theninj4** [comment]
How about when we set the static metadata like this:
```javascript
jsonApi.setConfig({
  meta: {
    description: "This block shows up in the root node of every payload"
  }
});
```
We could also support a synchronous function instead of an object:
```javascript
jsonApi.setConfig({
  meta: function(request) {
    return { };
  }
});
```
Would that be sufficient for your use cases?

**Comment by adamlc** [comment]
Well that would certainly suit my usecase. I have HTTP headers that come from my API Gateway (Tyk) like I'd like to expose as metadata.

**Comment by gauthierm** [comment]
@theninj4 Yeah, that would suit my use case.
