### ISSUE TITLE
Allow for multiple filter values to be combined in a comma-separated list

### ISSUE THREAD

**Issue by st3xupery** [holidayextras/jsonapi-server#183]
When referring to the [JSON API recommendations for filtering](http://jsonapi.org/recommendations/#filtering) it suggests:

> Multiple filter values can be combined in a comma-separated list: For example:
> `GET /comments?filter[post]=1,2 HTTP/1.1`

I understand that a similar result is achieved leveraging the Node querystring library as such:
`GET /comments?filter[post]=1&filter[post]=2 HTTP/1.1`

But in project I am currently working on it is not unusual to query the api with a filter list 100 values long and the redundancy of the same filter[xyz] tag despite easily automated adds a lot of length to a 100 entry long list query.

I've been able bridge the gap between the two types of filter list queries with essentially one line of code in  lib/filter.js See here: https://github.com/st3xupery/jsonapi-server/blob/development/lib/filter.js#L72

The build still passes all tests so there is no interuption to the latter method to doing a list filter query. I'd be happy to write an additional few tests to check that the former method works in all cases of the latter method too.

**Comment by theninj4** [comment]
This is a great suggestion. In all honesty I'm sure we used to have this feature, but it looks like there wasn't test coverage on it and we lost it over a refactor. If we can get a test to ensure we don't lose the feature again, then I'd love to merge it :+1:

**Comment by theninj4** [comment]
Thanks for the help :+1: Great work
