### ISSUE TITLE
Mask local routing addresses for an alias

### ISSUE THREAD

**Issue by st3xupery** [holidayextras/jsonapi-server#186]
When generating absolute links it would be ideal to mask the the addresses being generated to an alias that differs from the config parameters provided on server initialization. The port number I may provide to the server will not be the port number of the address someone reaches the API from. With nginx I proxy the traffic that hits the node server and I'd like the links to reflect that.

I've implemented such a change on [my fork here](https://github.com/st3xupery/jsonapi-server/tree/url-prefix-alias) with a field called urlPrefixAlias to be read at initialization. The changes to the code are minimal, doesn't interfere with existing tests. Let me know if I should write up some tests before I make a PR.

**Comment by theninj4** [comment]
Your changes look good, I'm not too worried about tests (it's very hard to test with the current test suite, which is geared towards a full-stack run journey via an example server) but some additional documentation might be good? Does the swagger documentation need any minor tweaking too? In summary - looks good, would merge :+1:

**Comment by st3xupery** [comment]
Great! Added some additional docs to configure.md and made sure the changes reflect in the swagger output.

**Comment by theninj4** [comment]
Thanks again for the contribution! :+1:
