### ISSUE TITLE
Asynchronous Processing

### ISSUE THREAD

**Issue by adamlc** [holidayextras/jsonapi-server#210]
We've come across a point where we need to do an operation that requires backend processing, the JSON API spec has quite a nice [recommendation](http://jsonapi.org/recommendations/#asynchronous-processing) around how do it. Is this something that you guys would be interested in implementing or is it out the scope of this project (also not sure how this would affect GraphQL stuff)? From what I can tell I can't see an obvious way of doing this at the moment.

Would love to hear your thoughts. Obviously it'll require some sort of custom handler or middleware I'd say, if this functionality isn't built in then it'll be nice to be able send custom responses and headers from handlers, which should cover this use case :)

**Comment by theninj4** [comment]
The asynchronous processing recommendation is really... odd. Firstly they suggest the process begins with `POST /photos`, however the response comes back with a type of `queue-jobs`, which doesn't match the `photos` type an API consumer may expect. Secondly the resource's self link is a bit odd (`/photos/queue-jobs/5234`), it doesn't match any well-known JSON:API routes. Here's their example for future reference incase the website changes:
```
POST /photos

{
  "data": {
    "type": "queue-jobs",
    "id": "5234",
    "attributes": {
      "status": "Pending request, waiting other process"
    },
    "links": {
      "self": "/photos/queue-jobs/5234"
    }
  }
}
```

The recommendation feels a bit... dirty. It doesn't really sit well with the core specification. I'd suggest a slight conceptual alteration to the recommendation that aligns much nicer with the JSON:API ideology, whereby you post to a `photo-requests` resource representing the consumer's place in the queue. At some point in the future, populate a relationship between their request and their resulting resource, enabling them to include or reference their photo without needing to query for another resource id. For example:

```
POST /photo-requests

{
  "data": {
    "type": "photo-requests",
    "id": "5234",
    "attributes": {
      "status": "Pending request, waiting other process"
    },
    relationships: {
      photo: {
        "links": {
          "self": "http://example.com/photo-requests/5234/relationships/photo",
          "related": "http://example.com/photo-requests/5234/photo"
        },
        "data": null
      }
    },
    "links": {
      "self": "/photo-requests/5234"
    }
  }
}
```

At some undetermined amount of time in the future, once the request has been completed, the photo-request resource would gain the relationship with the `photo` and the `related` link would connect, enabling the consumer to grab their photo from their well-known photo-request id:

http://example.com/photo-requests/5234/photo

This means when the API consumer requests to have their photo created, they get an immediate response with the URL at which their photo will become available at. There's no polling of an out-of-spec URL to get a HTTP header to go fetch another photo resource.

**Comment by adamlc** [comment]
@theninj4 to be honest that actually makes much more sense and is much cleaner. Thanks for your feedback, I'll certainly implement it in that way, much cleaner 😃
