### ISSUE TITLE
Add support for polymorphic relationships

### ISSUE THREAD

**Issue by nojacko** [holidayextras/jsonapi-server#212]
Hi. 

I'm trying to use jsonapi-server with an Ember app. We have a model with a relationship that is polymorphic. Ember supports this happily.

Below is the JSON-API payload that works. Is there away to have multiple types within a relationship using jsonapi-server?

Thanks

```javascript
{
    data: {
        id: "1",
        type: "event"
        attributes: {
            name: "Event",
        },
        relationships: {
            actions: {
                data: [
                    {
                        type: "eventActionTypeOne",
                        id: "2"
                    },
                    {
                        type: "eventActionTypeTwo",
                        id: "3"
                    }
                ]
            }
        },
    },
    included: [
        {
            type: "eventActionTypeOne",
            id: "2",
            attributes: {
                ...
            },
        },
        {
            type: "eventActionTypeTwo",
            id: "3",
            attributes: {
                ...
            },
        },
    ]
}
```

**Comment by theninj4** [comment]
This is an interesting one, it's a use case I haven't considered / encountered yet. Right now the above isn't going to work, however it doesn't feel like too big a step to support. I've got this Friday at work for 10% time, leave this with me and I'll see what I can do.

**Comment by nojacko** [comment]
Thanks @theninj4. You work fast!

**Comment by theninj4** [comment]
I've not updated the formal documentation yet, however in the interests of cutting a release and letting people try it, I'm going to defer it for a little bit.

Here's the usage snippet from the PR:

Some examples in this action:

```javascript
jsonApi.define({
  resource: 'tuples',
  handlers: tupleHandler,
  attributes: {
    media: jsonApi.Joi.many('articles', 'photos'),
    preferred: jsonApi.Joi.one('articles', 'photos')
  }
})
```

http://localhost:16006/rest/tuples?include=preferred
http://localhost:16006/rest/tuples?include=preferred.author
http://localhost:16006/rest/tuples?include=preferred.photographer
http://localhost:16006/rest/tuples?include=preferred.photographer,preferred.author

```
{
  tuples {
    preferred {
      ... on articles {
        author {
          firstname
        }
      }
      ... on photos {
        photographer {
          firstname
        }
      }
    }
  }
}
====
{
  "data": {
    "tuples": [
      {
        "preferred": {
          "author": {
            "firstname": "Rahul"
          }
        }
      },
      {
        "preferred": {
          "photographer": {
            "firstname": "Mark"
          }
        }
      }
    ]
  }
}
```

**Comment by nojacko** [comment]
Thanks @theninj4! This is really awesome!
