### ISSUE TITLE
should `handlers.close()` be officially documented and encouraged?

### ISSUE THREAD

**Issue by jokeyrhyme** [holidayextras/jsonapi-server#221]
I found that `jsonApi.close()` calls `handlers.close()`:
-   https://github.com/holidayextras/jsonapi-server/blob/v2.2.0/lib/jsonApi.js#L126

But this doesn't seem to be an officially documented part of the handler specification:
-   https://github.com/holidayextras/jsonapi-server/blob/v2.2.0/documentation/handlers.md

Is it worth adding this to the official handler specification?
Is implementing a `.close()` method something that we should encourage?

**Comment by jokeyrhyme** [comment]
Being able to close all open handles, handlers, timers, etc is an important part of addressing the FaaS use case I mention over in #219

**Comment by theninj4** [comment]
Gah, this auto-closed when I merged a PR. You're right, `.close()` is something that should be encouraged where applicable :+1:
