### ISSUE TITLE
Generate resources from Ember Models

### ISSUE THREAD

**Issue by bjornharrtell** [holidayextras/jsonapi-server#222]
I was thinking it might work to generate resources from Ember Models for maximum DRY. If it sound like a good idea I'm willing to try and implement it.

**Comment by theninj4** [comment]
It could be an interesting academic exercise, converting an Ember model to a Joi schema. A quick google search suggests people have tried to convert the other way (https://github.com/HelloWallet/joi-ember), I'm not sure how feasible it would be, or where it should live, but it does sound interesting :)

If you do give it a go and get it working, I'd be happy to link to it in the readme?

**Comment by bjornharrtell** [comment]
Ah! Didn't know Joi was a thing separate from jsonapi-server. The other way round could also be useful, but for me ember->joi would be nicer as I'd like to see development done top to bottom if possible. If I get anywhere I'll be sure to get back to you. :)

**Comment by bjornharrtell** [comment]
Relatedly I found this pretty cool generator that via JSON API can generate Ember Models: http://discuss.emberjs.com/t/ember-data-models-generator/10166.

So, can facilitate joi->ember via jsonapi-server.
