### ISSUE TITLE
missing git tag for v2.2.1

### ISSUE THREAD

**Issue by jokeyrhyme** [holidayextras/jsonapi-server#227]
Just noticed that NPM has v2.2.1, but there's no git tag for it. It would be super handy if you could add this in, probably against the commit where you bump the version to v2.2.1?

I find this makes linking to lines of code easier when I can lock it to a specific version. :)

**Comment by theninj4** [comment]
Oops, my bad. The latest commit in master was the merge for the v2.2.1 release, I'll tag it now :+1:

**Comment by jokeyrhyme** [comment]
Thanks, yay!
