### ISSUE TITLE
Last page link calculation is not accurate

### ISSUE THREAD

**Issue by yossialush** [holidayextras/jsonapi-server#230]
I've noticed that pagination link for the last page is miscalculated when the total result is even and
the limit is odd. For example: using this pagination params: page[limit]=5, I've got the following result:

"meta": {
    "page": {
      "offset": 0,
      "limit": 5,
      "total": 16
    }
  },
  "links": {
    "self": "/containers/12/templates?page[limit]=5",
    "last": "/containers/12/templates?page%5Blimit%5D=5&page%5Boffset%5D=14",
    "next": "/containers/12/templates?page%5Blimit%5D=5&page%5Boffset%5D=5"
  }

As you can see, last page has offset of 14 instead of 15.

**Comment by theninj4** [comment]
Interesting. I'll take a look :+1:
