### ISSUE TITLE
CORS is enabled, but URLs in links objects are relative.

### ISSUE THREAD

**Issue by Artanis** [holidayextras/jsonapi-server#24]
If a webpage hosted on one server fetches a resource hosted on another (`jsonapi-`)`server`, all the links are relative. Plugging these links into ajax requests will at best result in 404 errors, since the webpage will use its _own_ full URL to complete `jsonapi-server`'s relative URL.

For example, a webpage at `https://example.com` requests resource `http://jsonapi.server/api/articles` and gets some `articles` objects. Those articles have a to-one relationship `author` to `people`.

The webpage wants to resolve the author of `articles/1`, so it makes a request to the `related` link for that relationship, `/api/articles/1/author`. The request fills in the protocol and host name from it's own location and becomes `https://example.com/api/articles/1/author`.

----

I'd suggest making the URLs absolute at request time, rather than during configuration, no need to repeat  the DNS; you're basically telling the client, explicitly, that they can make further requests however they made the first one.

**Comment by hxoliverrumbelow** [comment]
I think you're right. I'll see what I can do this week :+1:
