### ISSUE TITLE
Filter for begins with

### ISSUE THREAD

**Issue by adamlc** [holidayextras/jsonapi-server#248]
Hey guys, would you find it useful to have a filter for begins with? I thought about using the "hat symbol" ```^```. I've quickly implemented this locally and it works fine!

If people are interested I can submit a PR. Also do we think this should be case insensitive or not?

**Comment by Aaronfischer** [comment]
@adamlc Where'd you "hack"/extend the filtering? I'm trying to see how I can write some custom filtering functionality but I'm not sure where to begin (or even find this).

**Comment by Redsandro** [comment]
@adamlc @Aaronfischer any update on this?

> _Where_'d you "hack"/extend the filtering? I'm trying to see how I can write some custom filtering functionality

**Comment by aaronfischer** [comment]
@redsandro I’m a bit unfamiliar with this at the moment, but here is my forked branch: https://github.com/Aaronfischer/jsonapi-server/commit/b6e4581ee5a9f24ebfd9c1ae2485a704023021d3

**Comment by adamlc** [comment]
@Redsandro this isn't something I really work on any more I'm afraid.

**Comment by Redsandro** [comment]
Thanks for the update, guys.
