### ISSUE TITLE
Examples not being loaded into MemoryHandler?

### ISSUE THREAD

**Issue by Aaronfischer** [holidayextras/jsonapi-server#249]
Had a couple questions regarding setup/config. (I'm pretty awful with dev-ops type stuff but this has been straight-forward so bless you for that!)

The docs make it sounds like as long as `handlers: new jsonApi.MemoryHandler(),` is used in the .define of a resource then anything within `examples: []` will be loaded into the "store". I've setup a few objects into this `examples` array but they are not populating.

Am I missing something? 

Here is my basic setup:
```
module.exports = function(app) {
  var jsonApi = require('jsonapi-server');

  jsonApi.setConfig({
    port: 16006,
    graphiql: false,
  });

  jsonApi.define({
    resource: 'drinks',
    handlers: new jsonApi.MemoryHandler(),
    attributes: {
      name: jsonApi.Joi.string(),
      img: jsonApi.Joi.string().uri(),
      quote: jsonApi.Joi.string(),
      temp: jsonApi.Joi.array().items(jsonApi.Joi.string()),
      wind: jsonApi.Joi.string(),
      time: jsonApi.Joi.array().items(jsonApi.Joi.string()),
      city: jsonApi.Joi.string(),
      country: jsonApi.Joi.string(),
      region: jsonApi.Joi.string(),
    },
    examples: [
      {
        id: 'aab14844-97e7-401c-98c8-0bd5ec922d93',
        type: 'drinks',
        name: 'Melon Patch',
        img: 'icon-icon-set-tall-mixed-drink',
        quote: 'I love Melon',
        temp: ['70','80','90','100'],
        wind: '',
        time: ['Morning','Noon'],
        city: '',
        country: '',
        region: '',
      },
    ],
  });

  jsonApi.start();
};
```

Also found that setting a `base: 'api'` throws a 404 when I attempt to hit /api/drinks.

Thanks!

**Comment by shaunc** [comment]
Joi doc of `uri()` says:

> Requires the string value to be a valid RFC 3986 URI.

Is `img` compliant? ... you might want to try:

    DEBUG=jsonApi:validation:error npm start

(or equiv) ... 404 will be generated if there is a validation error I think.

**Comment by Aaronfischer** [comment]
Hey @shaunc, that was part of it, it also didn't like returning empty strings.

I had assumed some kind of error would be thrown with bad data. I wouldn't have ever guessed to that was the problem. Thanks for the tip! Debug worked beautifully.
