### ISSUE TITLE
http2 support

### ISSUE THREAD

**Issue by braadworst** [holidayextras/jsonapi-server#251]
I am looking for an jsonapi server and this one looks very promising, but I don't see any way to use http2. Is this on the roadmap?

**Comment by wolfgang42** [comment]
`jsonapi-server` uses [`express`](https://www.npmjs.com/package/express) as its web framework, so that's where HTTP/2 support would come via. expressjs/express#2364 explains that you should attach express to an alternate http server such as `node-spdy` or `node-http2`.

**Comment by pmcnr-hx** [comment]
What @wolfgang42 said, @braadworst. Does that sound like a solution for you?

**Comment by pmcnr-hx** [comment]
Closing as we haven't heard from @braadworst and @wolfgang42's comment provides a solution.
