### ISSUE TITLE
Add resource configuration to disable automatic ID generation

### ISSUE THREAD

**Issue by wolfgang42** [holidayextras/jsonapi-server#259]
I have some resources whose IDs are integers auto-generated by the database server. I declare them as:
```javascript
jsonApi.define({
    resource: 'Order',
    attributes: {
        id: jsonApi.Joi.number().integer(),
        // Other attributes
    },
    handler: customHandler,
})
```

This causes a problem when I try to create a new ID: a UUID is automatically generated, but then fails validation because it is not an integer.
I therefore propose a new key in the resource definition, `generateId`, which can be set to `false` to disable autogenerating IDs. I have implemented this on my branch [create-generate-id](/holidayextras/jsonapi-server/compare/master...wolfgang42:create-generate-id), and it is working well for my use so far.
In the future this key could also be extended to take a function which returns an ID, so a project could define its own ID generation scheme. (For example using [`shortid`](https://www.npmjs.com/package/shortid); or perhaps even a content-addressable system where a data property is hashed to generate the ID.)

**Comment by st3xupery** [comment]
I have my own work around for this as an autoIncrement boolean setting in the resource config. I however check and delete the generated id in my own _data handler_ as such: 

`	if (this.autoIncrement)
		delete newResource.id;
`

So technically you can program this behavior without modifying the internals of the server. Obviously the by adjusting to this boolean internally feels a little more elegant.

**Comment by championswimmer** [comment]
would so totally love to see this happening
