### ISSUE TITLE
package.json requires eslint-plugin-promise twice

### ISSUE THREAD

**Issue by flyingbuddha** [holidayextras/jsonapi-server#263]
Hello 👋,

`eslint-plugin-promise` is defined twice in package.json with conflicting version numbers.
In dependencies it's listed as **^3.3.0**, whilst in devDependencies it's listed as **^2.0.0**.

What is the correct course of action? I feel that it should be removed from dependencies and the version bumped to **^3.3.0** in devDependencies.

**Comment by pmcnr-hx** [comment]
Apologies for the late reply @flyingbuddha. Just merged @jmeas's kindly contributed pull request to fix this.
