### ISSUE TITLE
GraphQL update operation not possible

### ISSUE THREAD

**Issue by maxschmeling** [holidayextras/jsonapi-server#285]
Updating objects using the GraphQL interface seems to be broken because of this line:

https://github.com/holidayextras/jsonapi-server/blob/c6822911d2bd30cc2e6578cff855bf591b91eb08/lib/graphQl/resolvers.js#L33

It references `args.tags.id`. `args.tags` is `undefined`.

Is this something I'm missing because I'm extremely new to GraphQL or is this just completely broken? It seems like `tags` should be something dynamic based on the schema.

**Comment by pmcnr-hx** [comment]
Can you provide a specific example that is failing? We have some tests covering GraphQL updates, which are passing, so it's hard to believe it broken for all cases.

**Comment by maxschmeling** [comment]
I believe it will fail anytime `resourceConfig.resource` is not `tags`. I could be missing something, but it seems hard-coded to work only for a resource called `tags`.

**Comment by maxschmeling** [comment]
If I change
```
const path = `${jsonApi._apiConfig.pathPrefix + resourceConfig.resource}/${args.tags.id}`
```
to
```
const path = `${jsonApi._apiConfig.pathPrefix + resourceConfig.resource}/${args[resourceConfig.resource].id}`
```
then my updates work.

**Comment by pmcnr-hx** [comment]
Thanks for the clarification @maxschmeling. I'll take a better look at the code and I'll come back to you.

**Comment by pmcnr-hx** [comment]
You are absolutely correct @maxschmeling. GraphQL support is still a bit immature and indeed the above was hardcoded for our automated tests which explained why the test passed. Would you like to submit a PR with the fix you propose above, so you get the credit? If not I can do it myself, but I would prefer if the commit came from you.

Thanks again for reporting the issue, diagnosing the problem and coming up with a fix and helping improve `jsonapi-server`.

**Comment by maxschmeling** [comment]
Awesome. Glad I could help.

I'll put together a PR today.
