### ISSUE TITLE
Typescript implementation of jsonapi-server

### ISSUE THREAD

**Issue by rbriois** [holidayextras/jsonapi-server#286]
I've found your project and have begun to play a little with it. 
We are certainly going to use it on our projects. 

however, we are using Typescript and we are wondering if you are willing to make a typescript version of it or just the needed typings for a good integration. 

Thanks in advance for your responses (and sorry if my english isn't accurate)

**Comment by pmcnr-hx** [comment]
We don't have any plans to re-implement `jsonapi-server` in TypeScript and it would not make sense to maintain both a JavaScript and a TypeScript version.

Maintaining the typings for ease of integration with TypeScript sounds like a good idea, and you're welcome to contribute a PR with those which would certainly consider for merging.
