### ISSUE TITLE
Support Node.js 8

### ISSUE THREAD

**Issue by paparomeo** [holidayextras/jsonapi-server#295]
Dev dependency on `v8-inspector` which in turn depends on `v8-debug`, which fails to compile on Node.js 8 is preventing us from support Node.js 8.

**Comment by vnen** [comment]
This is specially important now since Node.js 8.x is about to enter the Active LTS status.

**Comment by paparomeo** [comment]
I concur. I think we're going to have to disable our `v8-inspector` dependency for now.

**Comment by pmcnr-hx** [comment]
The `node-inspector` dependency was the culprit after. Removed and now Node.js 8 is supported in the latest release after #316. Closing.
