### ISSUE TITLE
Authentication with Passport sessions not possible

### ISSUE THREAD

**Issue by SphtKr** [holidayextras/jsonapi-server#304]
Thanks for this library, I'm very optimistic that it's going to fill my needs for a wide variety of applications.

I can't figure out though how it is possible to do authentication using sessions (especially) with Passport--which I think would probably be a common use case. This is how I am hooking up Passport:

    ...
    var app = jsonApi.getExpressServer();
    app.use(cookieParser());
    app.use(bodyParser());
    app.use(session({ secret: 'shh...' }));
    app.use(passport.initialize());
    app.use(passport.session());
    ...

The two hooks that seem to be available for use are `jsonApi.authenticate = function(request, callback){ ... }` and a `chainHandler`. These look great, _but_, in both cases the original request object has already been stripped out and replaced with the processed request representation. So, the `req.user` property that is added by Passport is not accessible. I notice that the original request is stuffed into the response object at some point, but the response is (probably reasonably) not passed to these handlers either.

There's a good chance I'm missing something and there's another way I should be doing this, open to suggestions. My use case is that I'm going to be building mostly Ember Data apps, and my authentication strategies may vary, in some cases using client certificates or Kerberos or others, which may be costly or inefficient to authenticate on every request. So I want my (human, browser) user to be able to authenticate once and then use the Passport session object to validate the user thereafter.

**Comment by cahva** [comment]
Your api should be stateless and you should use for example Json webtoken(jwt) in the header.

For getting the token (authentication), create a separate route where you have passport middleware. On succesfull authentication return token to user. Passport is only used on this stage. In jsonapi.authenticate you will validate and decode the token. In this stage you can fetch and set the user to request.user and that will be available throughout your api resources.

**Comment by adamlc** [comment]
Alternatively you could use something like [Kong](https://getkong.org/) to deal with the authentication. We're using both kong and jsonapi-server in production quite happily 👍

**Comment by SphtKr** [comment]
@adamlc Ooooh... Kong looks awesome!...unfortunately I don't think I can use it in the environment this time.

@cahva Ah...okay, did the research, read all the "tokens vs. cookies" stuff, and I think I get it now. Tried a JWT based authentication data flow and it works. Thanks!

There's an argument that the same issue/reasoning behind my original request applies for using something like `passport-jwt`--that is, the request properties added by Passport aren't accessible and that would be nice because the middleware could do all the work instead of rolling your own...but that wasn't my original issue so I'll go ahead and close.
