### ISSUE TITLE
Support non-uuid ids (integer ids, especially)

### ISSUE THREAD

**Issue by championswimmer** [holidayextras/jsonapi-server#321]
Allow using integer autoincrement ids, like most SQL databases prefer.

Right now a bit of monkey patching around a handler as said (on #320 and #259 ) can help us with this, but it isn't fully supporting GraphQL. (Validations fail, searches fail).

**Comment by paparomeo** [comment]
@championswimmer: I'm willing to merge #320 if we add some test coverage to it.

**Comment by pmcnr-hx** [comment]
Can we close this now that #320 has been merged @championswimmer?
