### ISSUE TITLE
Why do schema validation errors not return an error to the client?

### ISSUE THREAD

**Issue by wolfgang42** [holidayextras/jsonapi-server#330]
If a handler returns an invalid object, it is silently discarded by `responseHelper._enforceSchemaOnObject()`, with the only warning being a debug message. This causes a great deal of confusion when items silently go missing from responses. Is there a reason that it's set up this way? It makes much more sense to me that this would cause an error, something like:
```javascript
return callback({
  status: 500,
  code: 'EINVALIDITEM',
  title: 'Item in response does not validate',
  detail: {
    item: item,
    error: err.message
  }
})
```

I'd submit a pull request, but I wanted to ask first if this should be behind an option in case someone is relying on this behaviour.

**Comment by paparomeo** [comment]
I agree that the object shouldn't be discarded silently. Please feel free to submit a PR to fix this and we'll make a new major version release since this is a breaking change.
