### ISSUE TITLE
Joi@13 not compatible with Node@6

### ISSUE THREAD

**Issue by wolfgang42** [holidayextras/jsonapi-server#343]
Commit 784180d906a5ee4e6aefdc3feaae2ffc5c3b97fa specifically downgraded joi to continue Node 6 support, but #342 upgraded it again. It seems that CI didn't catch this because NPM doesn't check this for dependencies [unless `engine-strict` is set](https://docs.npmjs.com/files/package.json#engines). Yarn, however, *does* check regardless of `engine-strict` and will refuse to install jsonapi-server because of this.

**Comment by paparomeo** [comment]
Yes. That was one of the reasons why I had start using `yarn` in parallel with `npm`. I'm going to enable `engine-strict` for `npm` so this doesn't happen by accident in the future.
