### ISSUE TITLE
no way to set options for body-parser json

### ISSUE THREAD

**Issue by jstafford** [holidayextras/jsonapi-server#365]
body-parser offers a wide variety of options as documented at https://github.com/expressjs/body-parser#bodyparserjsonoptions

In particular I would like to set the json limit parameter to be larger than the default 100kb.

In my use case I have a recursive data structure that can sometimes be over 100kb.

I thought that perhaps I could override this somehow in express, but I have yet to find a way that works. 

I would be happy to match a pull request to add an additional optional config object to the apiConfig. Perhaps it could be called bodyParserOpts or just bodyparser.

**Comment by paparomeo** [comment]
I concur we should be able to pass these to option to Express. Thanks for your PR to address this. I hope to review and merge it soon.

**Comment by pmcnr-hx** [comment]
Closing this now that #366 has been merged.
