### ISSUE TITLE
ChainHandler needs way of getting resource

### ISSUE THREAD

**Issue by BryanHunt** [holidayextras/jsonapi-server#368]
I'm working on a ChainHandler that does authorization at the object level.  In order to check authorization on update and delete, you must first get the current resource from the database.  Right now, my ChainHandler opens a direct connection to MongoDB to read the current resource.  It would be nice if there were a function call to retrieve the resource within the ChainHandler without having to know how the resource is stored.

**Comment by paparomeo** [comment]
That sounds reasonable @BryanHunt. Pull requests are welcome: would you care to submit one to implement this functionality?

**Comment by BryanHunt** [comment]
As I looked at this further, there's not a good solution.  While there's a simple way to get the last handler in the chain, you have to construct a request object to use it, and you are limited to getting only the resource type you are currently acting on.

Ideally, there should be a generic API to resources that is independent of the request and could be easily formed by logic that knows nothing about web stuff.  This is certainly beyond the scope of this issue.

I think this issue can be closed.

**Comment by pmcnr-hx** [comment]
Thanks for looking into it @BryanHunt. At some point it would definitely be interesting to re-architect the core functionality to be independent of requests and provide hooks to customise it. However like you noted that won't be a trivial task.
