### ISSUE TITLE
why is "self" is different from "related" ?

### ISSUE THREAD

**Issue by olivierchatry** [holidayextras/jsonapi-server#376]
Using JSONAPI with ember, and it seems for some reason to bails on relationships query, because ember is using the "related" link instead of the "self".
```
"links":{
  "self":"http://localhost:3000/jsonapi/accounts/relationships/?members=-K5uq6i4s6CyiQF0ELV5",
  "related":"http://localhost:3000/jsonapi/accounts/?filter[members]=-K5uq6i4s6CyiQF0ELV5"
}
```

If I user the `related` link in postman, server return 403 ( relationship not valid for search ).

**Comment by olivierchatry** [comment]
Just read the documentation, and I understand now. But wouldn't it be better to just give the link with the actual id ( that is in the data ), rather than a filter ( that is not supported by the server ) ? Or I am missing something ?

**Comment by olivierchatry** [comment]
And closing the issue, it was my handler that was doing stupid stuff. Sorry.

**Comment by olivierchatry** [comment]
actually reopening, why does the server remove all foreign keys from the processed date ? 
```

**Comment by olivierchatry** [comment]
And again, sorry, just read the documentation about relationships, and it just hit me why :) Closing the task and again sorry.

**Comment by paparomeo** [comment]
No worries @olivierchatry. Apologies for not getting back to you sooner. Glad you figured it out!

**Comment by olivierchatry** [comment]
If it is of any interest for someone, here is my firebase adapter : https://github.com/olivierchatry/jsonapi-store-firebase
