### ISSUE TITLE
What to do with non-resource responses?

### ISSUE THREAD

**Issue by arunas-smala** [holidayextras/jsonapi-server#394]
I already asked it on stackoverflow: https://stackoverflow.com/questions/49754327/json-api-for-non-resource-responses

But I use `jsonapi-server` for my backend so I think you guys should know answer also..

**What to do with endpoints which are not about resources and does not have ID?**

For example, in our application, there is an endpoint `http://example.com/stats` which should return stats of **current logged in user**. Like

    {
      "active_things": 23,
      "last_login": "2017"
    }

There is no id for this "resource" (it's not actually a resource, is it?). Backend just collects some "stats" for logged in user and returns an object of stats. There many endpoints like this in this application, for example, we have *Notification center* page where the user can change email addresses for different notifications.

So frontend app (single-page-app) first has to get current values and it sends the request to `GET http://example.com/notification-settings`.

    {
      "notifications_about_new_thing": "arunas@example.com",
      "notification_about_other_thing": "arunas@example.com"
    }

And there are many more endpoints like this. The problem is - how to return these responses in JSONAPI format? There is no ID in these endpoints.

And the biggest question is - why nobody else is facing this issue (at least I cannot find any discussion about this)? :D All APIs I ever made has some endpoints which don't have "id".

I have two ideas, first is to fake `id`, like `"id": "doesnt_matter"`, the second - do not use `json-api` for these endpoints. But I don't like both of them.

**Comment by arunas-smala** [comment]
I need to read specification again :) I think I got the idea

**Comment by paparomeo** [comment]
Glad you figured it out @arunas-smala!
