### ISSUE TITLE
Implementing a SQL handler

### ISSUE THREAD

**Issue by Ramzeus** [holidayextras/jsonapi-server#72]
Hi,

I'm trying to implement an SQL handler.
But I have a problem that I wanted to ask about.

When I'm trying to create a SQL query I want to get a list of all the attributes that I should put in the query. But the attribute list contains things that are not attributes. Such as id, type and meta.
I see in the code that there is some special code that removes the non-attributes from the attribute list when generating the data item.
```
responseHelper._generateDataItem = function(item, schema) {

  var isSpecialProperty = function(value) {
    if (!(value instanceof Object)) return false;
    if (value._settings) return true;
    return false;
  };
  var linkProperties = Object.keys(schema).filter(function(someProperty) {
    return isSpecialProperty(schema[someProperty]);
  });
  var attributeProperties = Object.keys(schema).filter(function(someProperty) {
    if (someProperty === "id") return false;
    if (someProperty === "type") return false;
    if (someProperty === "meta") return false;
    return !isSpecialProperty(schema[someProperty]);
  });

  var result = {
    type: item.type,
    id: item.id,
    attributes: _.pick(item, attributeProperties),
    links: responseHelper._generateLinks(item, schema, linkProperties),
    relationships: responseHelper._generateRelationships(item, schema, linkProperties),
    meta: item.meta
  };

  return result;
};
```

It seems strange to me that the attribute list contains the non-attribute entries. And how about if I have an attribute called meta or type? Wouldn't that be a conflict?

The search() function of my handler looks something like this:
```
		search(request, callback) {
			let attributeKeys = Object.keys(request.resourceConfig.attributes);
			var sql = `
				SELECT ${attributeKeys.join(',')}
				FROM ${request.resourceConfig.resource}
			`;
			db.pool.query(sql, [], (err, res) => {
				let results = !err ? res.rows : [];
				results = _fixResult(request, results);
				return callback(err, results, results.length);
			});
		}
```

**Comment by pmcnr-hx** [comment]
Hi @Ramzeus! Are you aware of https://github.com/holidayextras/jsonapi-store-relationaldb?

**Comment by hxoliverrumbelow** [comment]
Hi @Ramzeus. Within the scope of your handler, `request.resourceConfig.attributes` maps directly to the resource definitions we've written (such as this: https://github.com/holidayextras/jsonapi-server/blob/master/example/resources/comments.js)

I agree that combining the attributes and the relationships into one object slightly complicates the use case for writing data into a relational database. As such, I've taken the time to provide that handler for the community, as @pmcnr-hx has said above. We're putting the final touches on that module right now and we're looking to ship it to production next week. On the flip side, combining attributes and relationships simplifies the use case for writing an object store handler.

It might be worth while automating the creation 2x new properties on `request.resourceConfig` to separate out the attributes and the relations, providing the option to chose which use case works best? If you think this'll help, I can make it happen.

**Comment by Ramzeus** [comment]
Oh, I was not aware about that project! I will take a look at it.
Thanks!
