### ISSUE TITLE
right way to hook handler CRUD operations?

### ISSUE THREAD

**Issue by futurist** [holidayextras/jsonapi-server#82]
Want to hook the handler method, e.g. CRUD, what's the right way? is there any API?

I see there's a `handlerEnforcer` wrapper, but seems need some hijack thing.

**Comment by theninj4** [comment]
Handlers are simply objects that have a bunch of functions. The documentation for creating a handler can be found here:
https://github.com/holidayextras/jsonapi-server/blob/master/documentation/handlers.md

Here's an example of how you might want to take most of a handlers core behaviour but re-implement one feature more efficiently: https://github.com/holidayextras/jsonapi-store-elasticsearch#getting-to-production

**Comment by futurist** [comment]
very good example, will go deep with that. thanks for the work!

**Comment by futurist** [comment]
do you mind using co/Promise/generator to this lib? I've created a PR to be use as below:

https://github.com/holidayextras/jsonapi-store-mongodb/compare/master...futurist:master

**usage:**

````
handler.before_create = function(type, doc){
  return new Promise(function(resolve, reject){
    if(type=='whitelist_type') resolve()
    else reject('some thing wrong, cannot create')
  })
}

handler.after_create = function(err, doc, next){
  if(err) do_something()
  else do_something_with(doc)

  next && next()
}
````
