### ISSUE TITLE
Joi default() not functioning

### ISSUE THREAD

**Issue by futurist** [holidayextras/jsonapi-server#84]
using mongodb-store, After set Joi default value as below:
````
......
attributes: {
    time: api.Joi.date().default(Date.now, 'time of creation'),
    age: api.Joi.number().default(18),
......
````
if omit the time/age when `POST`,  the database don't have default value specified above.

**Comment by theninj4** [comment]
This is correct, we're only using Joi to pick up validation errors at the moment. It should be fairly simple to take the Joi-adjusted object after passing validation.

**Comment by futurist** [comment]
I see. and please check the PR #85  above, it's worked here, but don't strictly tested.

**Comment by theninj4** [comment]
Ah amazing! Thanks for the contribution, sorry I didn't see your PR sooner, I've been crazy busy over the last few days.
