### ISSUE TITLE
Rename `CHANGELOG.md` or make it Markdown

### ISSUE THREAD

**Issue by pmcnr-hx** [holidayextras/jsonapi-server#93]
Either rename `CHANGELOG.md` to `CHANGELOG.txt` or make it proper Markdown, otherwise GitHub renders it nastily. While we're at it, it'll probably make sense to reorder in chronologically inverse order with the most recent entries first.

**Comment by theninj4** [comment]
Haha, you're absolutely right! Doh.

**Comment by pmcnr-hx** [comment]
This has been fixed in #98.
