### ISSUE TITLE
server responds to OPTIONS method with 404

### ISSUE THREAD

**Issue by moeabm** [holidayextras/jsonapi-server#94]
The browser is sending a preflight OPTIONS request that returns 404. This seems to be a CORS. I could very well be doing something wrong but cannot find any docs on how to implement CORS on the server.

**Comment by moeabm** [comment]
This may be out of the scope of this project. I'm just using a reverse proxy to put the server on same host, port and protocol as the client (ember-data).

**Comment by theninj4** [comment]
Ah. The current behaviour is to set the following headers on every response:
```
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "*"
```
...however we're fronting all our environments with nginx which will be handling OPTIONS requests for us. jsonapi-server should be responding to the OPTIONS request.

**Comment by theninj4** [comment]
The default headers should now enable CORS out-of-the-box :+1:

**Comment by moeabm** [comment]
Very nice. Thank you.
